### ISSUE TITLE
If column is set to TIMESTAMP_NTZ in snowflake it cannot be converted to Date

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-snowflake#130]
Error:

`NotImplementedError: Default TypeEngine.as_generic() heuristic method was unsuccessful for target_snowflake.snowflake_types.TIMESTAMP_NTZ. A custom as_generic() method must be implemented for this type class.`

To reproduce
1. Take any table that's already in Snowflake smoke-test works, run `meltano run tap-smoke-test target-snowflake`
```
  - name: tap-smoke-test
    variant: meltano
    pip_url: git+https://github.com/meltano/tap-smoke-test.git
    config:
      streams:
      - stream_name: animals
        input_filename: https://gitlab.com/meltano/tap-smoke-test/-/raw/main/demo-data/animals-data.jsonl
```
2. Change one of the metadata fields that has the column type of TIMESTAMP_NTZ to DATE see below for an example
```ALTER TABLE MELTANO_DATABASE.ZENOTI.ANIMALS ADD COLUMN _SDC_EXTRACTED_AT_TEMP DATE;
UPDATE MELTANO_DATABASE.ZENOTI.ANIMALS  SET _SDC_EXTRACTED_AT_TEMP = TO_DATE(SDC_EXTRACTED_AT);
ALTER TABLE MELTANO_DATABASE.ZENOTI.ANIMALS  DROP COLUMN _SDC_EXTRACTED_AT;
ALTER TABLE MELTANO_DATABASE.ZENOTI.ANIMALS  RENAME COLUMN _SDC_EXTRACTED_AT_TEMP to _SDC_EXTRACTED_AT;
```
3. Run it again `meltano run tap-smoke-test target-snowflake` You'll get the same error
