### ISSUE TITLE
Snowflake destination table created with incorrect NUMBER precision

### ISSUE THREAD

**Issue by jpuris** [MeltanoLabs/target-snowflake#77]
External ref: [Slack thread](https://meltano.slack.com/archives/C01TCRBBJD7/p1688928660240179) on Meltano Slack community

meltano.yml

```yaml
# ...
  extractors:
  - name: tap-oracle
    pip_url: git+https://github.com/christianelliott/pipelinewise-tap-oracle.git
# ...
  loaders:
  - name: target-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-target-snowflake
# ...
```

For example, `--dump=catalog`'s one of the fields in stream are

```
            "AMT_EXCL_TAX": {
                "multipleOf": 0.0001,
                "type": [
                    "null",
                    "number"
                ]
            },
```

but in snowflake it is created as

```sql
AMT_EXCL_TAX NUMBER(38,0)
```

while the correct field would be

```sql
AMT_EXCL_TAX NUMBER(34, 4)
```

Please let me know, if there is anything in addition I can gather to make this easier to troubleshoot.
I can also try to produce a MRE, if absolutely necessary.
